Add 'theme' option and two new themes
timoschwarzer/gitlab-monitor pull request #151
Opened 2020-09-02 17:47 UTC by lscheibel

This PR will add the ability to create themes and adds two new ones already. Also adds a background to the standard theme and explain how to create custom themes in `THEMING.md`. 

PS: please check for spelling errors 😬

nord-light:
![image](https://user-images.githubusercontent.com/44374653/92016741-13e40300-ed53-11ea-918a-15e2292866f0.png)

nord-dark:
![image](https://user-images.githubusercontent.com/44374653/92017664-67a31c00-ed54-11ea-9996-71e2e6804a83.png)
![image](https://user-images.githubusercontent.com/44374653/92017762-86091780-ed54-11ea-82d7-931d87452e63.png)

2020-09-03 15:34 UTC, timoschwarzer requested changes

2020-09-03 15:34 UTC, timoschwarzer commented on CONFIGURATION.md
> +# Can be generated here: https://gitlab.com/profile/personal_access_tokens At least api_read scope is needed
Please use `https://gitlab.example.com/profile/personal_access_tokens` to make clear that you cannot get access tokens for your own instance on gitlab.com

2020-09-03 15:34 UTC, timoschwarzer commented on CONFIGURATION.md
> +# Predefined Theme to use, if not set, the default theme will be used.
```suggestion
# Predefined theme to use. If null, the default theme will be used.
```

2020-09-03 15:34 UTC, timoschwarzer commented on CONFIGURATION.md
> +# but please feel free to submit your own theme as 'src/themes/<your-theme-name>.theme.scss'!
```suggestion
# You can override styles in the settings or submit your own theme here: https://git.io/JUOFb
```

2020-09-03 15:34 UTC, timoschwarzer commented on THEMING.md
> +If you think that you're custom styles would be appreciated but others too, you can submit your own theme as a pull-request!
```suggestion
You can submit your own themes as a pull request to make it available to all users.
```

2020-09-03 15:34 UTC, timoschwarzer commented on THEMING.md
> +and add your theme name as a wrapper around everything that you'll add.
```suggestion
and add a global class selector named after your theme.
```

2020-09-03 15:34 UTC, timoschwarzer commented on THEMING.md
> +To use your theme simply add the name of your theme in the config:
```suggestion
Enable your theme in your configuration to see your changes:
```

2020-09-03 15:34 UTC, timoschwarzer commented on THEMING.md
> +We are using [css-custom-properties](https://developer.mozilla.org/en-US/docs/Web/CSS/--*) for variables.
```suggestion
Themes use [CSS Custom Properties](https://developer.mozilla.org/en-US/docs/Web/CSS/--*) for variables.
```

2020-09-03 15:34 UTC, timoschwarzer commented on THEMING.md
> +There are quite a few variables out there to make your life easier.
```suggestion
There are quite a few variables out there to make theme development easier.
```

2020-09-03 15:34 UTC, timoschwarzer commented on THEMING.md
> +or look in the dev-tools.
```suggestion
Take a look at existing themes for a list of variables or check out your browser's dev tools.
```

2020-09-03 15:34 UTC, timoschwarzer commented on THEMING.md
> +
```suggestion
```

2020-09-03 15:34 UTC, timoschwarzer commented on THEMING.md
> +to create pull-requests to update and fix any issues with any of the themes.
```suggestion
```

2020-09-03 15:34 UTC, timoschwarzer commented on src/themes/nord-dark.theme.scss
> +@import url('https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@700&family=Roboto:ital@0;1&display=swap');
Please add fonts as a direct dependency

2020-09-03 15:34 UTC, timoschwarzer commented on src/themes/nord-light.theme.scss
> +@import url('https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@700&family=Roboto:ital@0;1&display=swap');
fonts

2020-09-04 18:56 UTC, lscheibel commented on THEMING.md
> +If you think that you're custom styles would be appreciated but others too, you can submit your own theme as a pull-request!
Changed 'it' to 'them'

2020-09-08 17:29 UTC, lscheibel commented
All done

2020-09-09 08:14 UTC, timoschwarzer commented
This needs a rebase

2020-09-15 19:39 UTC, lscheibel commented
This PR now also fixes a bug introduced with #156 where clearTimeout was called incorrectly leading to settings being applied incompletely, forcing a reload

2020-09-15 19:52 UTC, merged

2020-09-15 19:53 UTC, timoschwarzer commented
Thanks!