Add 'orderBy' option
timoschwarzer/gitlab-monitor pull request #152
Opened 2020-09-03 08:02 UTC by lscheibel

Adds orderBy option and 4 possible values: 'lastActivity', 'created', 'name', 'nameWithNamespace'

resolves #80

2020-09-03 15:38 UTC, timoschwarzer requested changes

2020-09-03 15:38 UTC, timoschwarzer commented on CONFIGURATION.md
> +# How to order the displayed projects. Accepts: lastActivity, created, name, nameWithNamespace
```suggestion
# Project display order. Possible values: lastActivity, created, name, nameWithNamespace
```

2020-09-03 15:38 UTC, timoschwarzer commented on src/components/app.vue
> +            `Config.orderBy: Could not resolve sort method, using 'lastActivity' instead.`,
```suggestion
            `Config.orderBy: Invalid configuration value "${Config.root.orderBy}", falling back to lastActivity`,
```

2020-09-03 15:38 UTC, timoschwarzer commented on src/components/app.vue
> +            `Available methods are ${Object.keys(sortMethods).join(', ')}`
```suggestion
            `Possible values: ${Object.keys(sortMethods).join(', ')}`
```

2020-09-03 15:41 UTC, timoschwarzer commented
Would be nice if you'd implement an `orderByDesc: bool` option.

e.g.

```js
if (orderByDesc) {
  byMethod = (a, b) => sortMethods[Config.root.orderBy](b, a)
}
```

2020-09-04 18:51 UTC, lscheibel commented
All done

2020-09-05 06:36 UTC, timoschwarzer requested changes

2020-09-05 06:36 UTC, timoschwarzer commented on CONFIGURATION.md
> +# Wether to order displayed projects descending
"Sort in descending order"

2020-09-08 17:29 UTC, lscheibel commented
Changed wording

2020-09-09 08:15 UTC, merged