Change the order of the pipeline stages
timoschwarzer/gitlab-monitor pull request #160
Opened 2020-12-03 10:29 UTC by Keroth

We had the problem, that the pipeline was displayed in the wrong order for us. So I implemented a switch to reverse the order. maybe other people could also find this usefull. 

Before:
![before](https://user-images.githubusercontent.com/3768372/100997131-38ba6300-355a-11eb-8ed4-75b3510f2c53.png)

After:
![after](https://user-images.githubusercontent.com/3768372/100997237-55ef3180-355a-11eb-83ba-0dc021b84d36.png)

This feature is controled by setting the parameter `reverseStages` to either `true` (reverse the order) or `false` (do nothing).

Input is very appreciated

Regards
Keroth

2020-12-03 10:46 UTC, timoschwarzer commented
Hmm, that's odd. Thank you for the PR! But I'd rather like to find out why the order was off in the first place... Do you have any idea why this was the case?

2020-12-03 12:52 UTC, philip-n commented
We recently upgraded from an older version (12.9?) to gitlab 13.6. I'm quite sure that before, the stages were sorted left-to-right in the monitor, whereas now they are displayed right-to-left (i.e. jobs from last stage displayed on the left). Gitlab-monitor was not changed.

So my guess would be that at some point, the output from gitlab may have changed order?

I'd be happy for the contribution in the PR to become available in some way. Preferred way would be to define the default behavior that stages are sorted (which should imo be left-to-right) and make sure this is always the case, and then add the option to reverse it (for personal preferences).

2020-12-03 17:34 UTC, timoschwarzer commented
I took a look at the API response for pipeline jobs and the stages are in reversed order indeed. I'd propose to sort the jobs by ID instead of reversing them though. This would prevent breaking the order again nn case GitLab "fixes" the API.

2020-12-04 07:45 UTC, Keroth commented
ok I thought this was a problem with our gitlab instance. I will implement the sorting on the weekend.

2020-12-04 13:38 UTC, Keroth commented
I changed it. I hope this is ok, I'm not that used to js.

2020-12-04 13:59 UTC, timoschwarzer requested changes

2020-12-04 13:59 UTC, timoschwarzer commented on src/components/pipeline-view.vue
> +        });
```suggestion
        this.jobs.sort((j1, j2) => j1.id - j2.id);
```

2020-12-04 14:00 UTC, merged

2020-12-04 14:00 UTC, timoschwarzer commented
@Keroth thank you very much! :)