Add test-report
timoschwarzer/gitlab-monitor pull request #164
Opened 2021-01-27 11:58 UTC by gpaOliveira

As a QA, I'm also interested in the test report from a pipeline, and since my team Gitlab show it on a pretty page I also fetched it via the API.

Following a good example of another PR (https://github.com/timoschwarzer/gitlab-monitor/pull/162), I also added a proper flag for it (showTestReport) and made sure it will only show if there's data available.

I also wanted to add the suites/tests as an accordion below that summary, but couldn't make it pretty enough and maybe unnecessary (since one can just click on the summary and see details on Gitlab), but in any case, open for suggestions there.

![image](https://user-images.githubusercontent.com/380111/105987540-b3a58300-609e-11eb-9d08-d334dab1c9f5.png)

2021-01-28 00:06 UTC, timoschwarzer commented
Thanks for the suggestion!

What do you think of moving the test coverage into the next line and using these icons for the test report stats respectively:

https://gitlab.com/gitlab-org/gitlab-svgs/-/blob/main/sprite_icons/status_success.svg
https://gitlab.com/gitlab-org/gitlab-svgs/-/blob/main/sprite_icons/status_skipped.svg
https://gitlab.com/gitlab-org/gitlab-svgs/-/blob/main/sprite_icons/status_failed.svg
https://gitlab.com/gitlab-org/gitlab-svgs/-/blob/main/sprite_icons/error.svg

2021-01-28 00:07 UTC, timoschwarzer commented
...and maybe even hiding report stats that are 0.

2021-01-28 09:27 UTC, gpaOliveira commented
Good suggestions! 

I can hide when 0 sure, but I have no clue how to add those new icons to the src/assets/icons.svg file (so I can reuse `gitlab-icon` component properly). Any tips there are appreciated, or even a patch with just those added lines that I can add to a commit.

About the move of the coverage part, what should happen if we have `showTestReport == false && showCoverage == true`? I assume one would like to keep the coverage in the same place as of today... right?

2021-01-28 13:31 UTC, timoschwarzer commented
> I can hide when 0 sure, but I have no clue how to add those new icons to the src/assets/icons.svg file (so I can reuse `gitlab-icon` component properly). Any tips there are appreciated, or even a patch with just those added lines that I can add to a commit.

I've updated the icon set to the latest version. You should be able to use the after rebasing your branch on main (remember to pull main before).

> About the move of the coverage part, what should happen if we have `showTestReport == false && showCoverage == true`? I assume one would like to keep the coverage in the same place as of today... right?

Yeah, right. Then just remove the separator line as it would be confusing when having multiple pipelines, wouldn't it?

2021-01-29 13:56 UTC, gpaOliveira commented
Ok here it goes!

I took some liberty on the icons, somehow the "status_*" were all the same for me. And removed the separator line. And made everything 

**Icons sample (hacked version, current code will only show the icon+number if that item is > 0):**

![image](https://user-images.githubusercontent.com/380111/106282929-8cd38200-6241-11eb-8d21-029e1b6986e5.png)

**Current sample:**

![image](https://user-images.githubusercontent.com/380111/106283324-14b98c00-6242-11eb-96bf-5109915260ef.png)

2021-01-29 15:15 UTC, timoschwarzer requested changes
Thank you! :)
A few minor suggestions and then it should be ready to be merged.

2021-01-29 15:15 UTC, timoschwarzer commented on src/components/pipeline-view.vue
> +    <test-report :pipeline="pipeline" />
```suggestion
    <test-report v-if="showTestReport && pipeline.test_report !== null" :pipeline="pipeline" />
```

2021-01-29 15:15 UTC, timoschwarzer commented on src/components/test-report.vue
> +  <div v-if="showTestReport && pipeline.test_report !== null">
```suggestion
  <div>
```

2021-01-29 15:15 UTC, timoschwarzer commented on src/components/test-report.vue
> +    }
```suggestion
```

2021-02-01 12:50 UTC, gpaOliveira commented
Resolved all conversations, addressed on the new commit @timoschwarzer

2021-02-04 09:40 UTC, merged

2021-02-04 09:40 UTC, timoschwarzer commented
Thank you very much! :)